name: CD - Build & Push Services

on:
  workflow_dispatch: {} # Enable manual runs
  push:
    branches: [
      main
    ]
    

env:
  # GitHub is case-insensitive, and have inconsistent casing in their API.
  # We need lowercase for the image prefix.
  # You can either calculate the namespace from the repository name, or use the owner and name directly
  # Repo link: https://github.com/LarsGJobloop/nix-devcontainer-example
  # Hardcoded to reduce inline bash scripting.
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/BJ-Kodehode/discord-bot-dev  

jobs:
  # This job is used to build and push the changes detected in the changes job.
  # The output from the changes job is used to create a matrix of services to build and push.
  # It's in essence the steps you would have to run in your own terminal.
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push multi-arch
        id: build-push
        # Mind the platforms here, they are to support both amd64 and arm64 development platforms.
        run: |
          IMAGE="ghcr.io/bj-kodehode/discord-bot-dev/discord-bot"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t $IMAGE:${{ github.sha }} \
            -t $IMAGE:latest \
            .